In [29]:
%env CUDA_VISIBLE_DEVICES=""

env: CUDA_VISIBLE_DEVICES=""


In [49]:
import torch
torch.autograd.set_detect_anomaly(True)
input_data = torch.tensor([[1.5, 1.3]], requires_grad=True) # This data produces [-0.6, -0.8] log probability
#input_data = torch.tensor([[0.01, -700]], requires_grad=True)  # This data produces [0, -700] log probability
target_prob = torch.tensor([[1.0, 0.0]], requires_grad=True)
input_logprob = torch.nn.functional.log_softmax(input_data, dim=1)
print(input_logprob)
kl_loss = torch.nn.KLDivLoss(reduction="batchmean")
output = kl_loss(input_logprob, target_prob)
print(output)
output.backward()

tensor([[-0.5981, -0.7981]], grad_fn=<LogSoftmaxBackward0>)
tensor(0.5981, grad_fn=<DivBackward0>)


RuntimeError: Function 'XlogyBackward0' returned nan values in its 1th output.

tensor([[   0., -100.]], grad_fn=<LogSoftmaxBackward0>)

In [7]:
import torch
torch.autograd.set_detect_anomaly(True)
input1 = torch.tensor([0.0], requires_grad=True)
input2 = torch.tensor([0.0], requires_grad=True)
output = torch.special.xlogy(input1, input2)
output.backward()
print(input2.grad)

/home/kotech/venv-torch1.13/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in XlogyBackward0. Traceback of forward call that caused the error:
  File "/home/kotech/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kotech/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/traitlets/config/application.py", line 982, in launch_instance
    app.start()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loo

RuntimeError: Function 'XlogyBackward0' returned nan values in its 1th output.

In [6]:
def my_kl_loss(input_, target):
    return torch.mean(torch.special.xlogy(target, target) - target*input_)

import torch
torch.autograd.set_detect_anomaly(True)
input_data = torch.tensor([[1.5, 1.3]], requires_grad=True) # This data produces [-0.6, -0.8] log probability
target_prob = torch.tensor([[1.0, 0.0]], requires_grad=True)
input_logprob = torch.nn.functional.log_softmax(input_data, dim=1)
print(input_logprob)
kl_loss = torch.nn.KLDivLoss(reduction="batchmean") # nan gradient
#output = kl_loss(input_logprob, target_prob)
output = my_kl_loss(input_logprob, target_prob)
print(output)
output.backward()

tensor([[-0.5981, -0.7981]], grad_fn=<LogSoftmaxBackward0>)
tensor(0.2991, grad_fn=<MeanBackward0>)


/home/kotech/venv-torch1.13/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in XlogyBackward0. Traceback of forward call that caused the error:
  File "/home/kotech/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kotech/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/traitlets/config/application.py", line 982, in launch_instance
    app.start()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/home/kotech/venv-torch1.13/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loo

RuntimeError: Function 'XlogyBackward0' returned nan values in its 1th output.